name: Build and deploy Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DANOPZ_BOT_KEY }}
          fetch-depth: 1
      - name: npm build
        uses: actions/setup-node@v1
        with:
            node-version: 12
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DANOPZ_BOT_KEY }}
          user_name: 'danopz-bot'
          user_email: 'bot@copynpaste.de'
          publish_branch: gh-pages
          publish_dir: ./public
          cname: danopz.de
          allow_empty_commit: false
