name: Build and deploy Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DANOPZ_BOT_KEY }}
          fetch-depth: 1
      - name: npm build
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: public
          path: public
      - uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DANOPZ_BOT_KEY }}
          user_name: "danopz-bot"
          user_email: "bot@copynpaste.de"
          publish_branch: gh-pages
          publish_dir: ./public
          cname: danopz.de
          allow_empty_commit: false
